# Generated by Django 4.0.2 on 2022-02-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg', '0003_remove_chat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_username', models.CharField(max_length=1000)),
                ('text', models.CharField(max_length=1000)),
                ('time', models.TimeField()),
            ],
        ),
    ]
