# Generated by Django 4.0.2 on 2022-03-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg', '0004_globalchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('money', models.IntegerField()),
            ],
        ),
    ]
