# Generated by Django 4.0.2 on 2022-05-06 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dg', '0007_alter_message_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='global_chat')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('size', models.IntegerField(blank=True, default=None, null=True)),
                ('message', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='dg.globalchat')),
            ],
        ),
    ]
